# Generated by `react-native-darwin-init`.
#
# The Xcode project is generated rather than committed, so there is no
# binary-ish pbxproj to merge. Run it once; `pod install` integrates with the
# result. Re-run it whenever you add a file to the app target.
#
#   gem install xcodeproj && ruby macos/generate-project.rb

require 'fileutils'
require 'xcodeproj'

root = File.dirname(__FILE__)
path = File.join(root, '__APP_NAME__.xcodeproj')
FileUtils.rm_rf(path)

project = Xcodeproj::Project.new(path)
target = project.new_target(:application, '__APP_NAME__', :osx, '14.0')

group = project.new_group('__APP_NAME__', '__APP_NAME__')
%w[main.m AppDelegate.mm].each do |file|
  target.add_file_references([group.new_reference(file)])
end
group.new_reference('AppDelegate.h')
group.new_reference('Info.plist')

target.build_configurations.each do |config|
  s = config.build_settings
  s['PRODUCT_BUNDLE_IDENTIFIER'] = '__BUNDLE_ID__'
  s['INFOPLIST_FILE'] = '__APP_NAME__/Info.plist'
  s['CODE_SIGN_ENTITLEMENTS'] = '__APP_NAME__/__APP_NAME__.entitlements'
  s['MACOSX_DEPLOYMENT_TARGET'] = '14.0'
  s['CLANG_ENABLE_OBJC_ARC'] = 'YES'
  s['CODE_SIGN_IDENTITY'] = '-'
  s['CODE_SIGNING_REQUIRED'] = 'NO'
  s['CODE_SIGNING_ALLOWED'] = 'NO'
  s['ALWAYS_SEARCH_USER_PATHS'] = 'NO'
  s['LD_RUNPATH_SEARCH_PATHS'] = ['$(inherited)', '@executable_path/../Frameworks']
  s['ONLY_ACTIVE_ARCH'] = 'YES'
end

project.save
puts "generated #{path}"
