/**
 * Generated by `react-native-darwin-init`.
 *
 * Metro resolves one platform per request, and under `platform: 'macos'` it
 * never considers a `.ios.js` file -- so the twenty-odd modules React Native
 * ships only as `.ios` are simply not found. `getMacOSConfig` adds iOS as the
 * fallback, which is right because macOS shares the Apple-platform module
 * surface.
 *
 * It *wraps* any resolveRequest already on the config rather than replacing it,
 * so merging with a framework's own config is safe.
 *
 * @format
 */

const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const {getMacOSConfig} = require('__RN_PKG__/macos/metro-config');

const config = getDefaultConfig(__dirname);

module.exports = mergeConfig(config, getMacOSConfig(config));
